#!/bin/bash

## This script is designed to safely re-point a symlink from one file to
## another file.
##
## Author: Ted Wod (twood8)
## Date: 2012-12-05

if [ -z $1 ] || [ -z $2 ]; then
    echo -e "Point link to new location"
    echo -e "Usage:\n\tlnmv link_name new_location"
    exit 1
fi

temp="$1.`date +%N`"
mv $1 $temp
ln -s $2 $1
rm $temp
